--[[  Generated by FAF Map Editor                                              ]]--
-- Table of which resources belong to which player, it is sorted in such a way that the first line
-- corresponds to player one, the second to player 2 and so on...

maxPlayerOnMap = 8




-- Line number is 10 + armynumber for the mexes in the table
spwnMexArmy = {		{102,115,126,19,30,44,61,62,63,65,66,72,73,76,86,99},
                    {119,26,27,41,51,60,69,70,77,79,81,82,83,90,93,95},
                    {100,101,110,113,116,117,24,34,38,40,42,43,56,88,97,98},
                    {02,03,09,104,107,111,114,118,120,123,124,22,64,68,80,87},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {}}



-- Line number is 30 + armynumber for the hydros in the table
spwnHydroArmy = {	{},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {}}


-- RESOURCE SCALING OPTIONS
-- exampleMexes = {{1,2},{3,4},{5,6}},        -- exampleMexes = {{1,2}}
-- exampleMexes = {{a},{b},{c}},              -- exampleMexes = {{a}}
-- option key=1 : removes a+b+c               -- option key=1 : removes a
-- option key=2 : spawn a, removes b+c        -- option key=2 : spawns a
-- option key=3 : spawn a+b, removes c
-- option key=4 : spawn a+b+c

extraHydros = {{}}

extraMexes = {{}}

middleMexes = {{},{},{}}

sideMexes = {{},{},{}}

underwaterMexes = {{},{},{}}

islandMexes = {{},{},{}}

expansionMexes = {{},{},{}}

coreMexes = {{}}

extraBaseMexes = {{}}

topSideMexes = {{},{},{}}

bottomSideMexes = {{},{},{}}

forwardCrazyrushMexes = {}

crazyrushOneMexes = {}

